version: "3.8"
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
    environment:
      USE_PY_SERVICE: "false" 
      NODE_SERVICE_URL: http://tag-analysis-service:4001
      PY_ANALYSIS_SERVICE_URL: http://py-service:5001

  tag-analysis-js-service:
    build:
      context: ./tag-analysis-service/js-services
      dockerfile: Dockerfile
    ports:
    - "4002:4001"

  tag-analysis-py-service:
    build:
      context: ./tag-analysis-service/py-services
      dockerfile: Dockerfile
    ports:
    - "5001:5001"